import os
import numpy as np
from PIL import Image
from flask import Flask, request, jsonify
import tensorflow as tf

app = Flask(__name__)
# Load model without compiling to avoid version compatibility issues
model = tf.keras.models.load_model("model.keras", compile=False)

@app.get("/summary")
def summary():
    return jsonify({
        "status": "ok",
        "image_size": "150x150",
        "class_names": ['damage', 'no_damage'],
        "model_type": "Alternate-Lenet-5 CNN architecture"
    })

# The code below was generated by AI; see [1].
def preprocess_image(file_storage):
   img = Image.open(file_storage.stream)
   if img.mode != 'RGB':
      img = img.convert('RGB')
   img = img.resize((150, 150))
   x = np.asarray(img, dtype=np.float32) / 255.0
   x = np.expand_dims(x, axis=0)
   return x

def predict_probability(x):
    preds = model.predict(x, verbose=0)
    prob_damage = float(np.squeeze(preds))  
    return prob_damage

@app.post("/inference")
def inference():
    if "image" not in request.files:
        return jsonify({"error": "no 'image' file provided"}), 400
    
    try:
        x = preprocess_image(request.files["image"])
        prob_damage = predict_probability(x)
        prob_no_damage = 1.0 - prob_damage
        predicted_class = "no_damage" if prob_damage >= 0.5 else "damage"
        
        return jsonify({
            "prediction": predicted_class,
            "probabilities": {
                "damage": prob_damage,
                "no_damage": prob_no_damage
            }
        })

    except Exception as e:
        return jsonify({"error": str(e)}), 500

if __name__ == "__main__":
    host = os.environ.get("HOST", "0.0.0.0")
    port = int(os.environ.get("PORT", "5000"))
    app.run(host=host, port=port, debug=False)